config/routes.rb
Rails.application.routes.draw do
  resources :cards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :name, presence: true
  validates :rate, presence: true
  validates :group, presence: true
  validates :attack, presence: true
  validates :intellect, presence: true
  validates :suppression, presence: true
  validates :cost, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :rate, :group, :attack, :intellect, :suppression, :comment, :image, :cost, :image_cache, :remove_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_on(model, attr, css_class = "formError")
    error_html = ""

    if model.errors[attr].blank?
      return error_html
    end

    error_html = ""

    model.errors[attr].each do |error|
      error_html += "<div class='#{css_class}'>#{model.class.human_attribute_name(attr)}#{error}</div>"
    end
    return error_html.html_safe
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(card) do |f| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= error_messages_on(f.object, :name)%>
  </div>

  <div class="field">
    <%= f.label :rate %>
    <%= f.number_field :rate %>
    <%= error_messages_on(f.object, :rate)%>
  </div>

  <div class="field">
    <%= f.label :group %>
    <%= f.number_field :group %>
    <%= error_messages_on(f.object, :group)%>
  </div>

  <div class="field">
    <%= f.label :attack %>
    <%= f.number_field :attack %>
    <%= error_messages_on(f.object, :attack)%>
  </div>

  <div class="field">
    <%= f.label :intellect %>
    <%= f.number_field :intellect %>
    <%= error_messages_on(f.object, :intellect)%>
  </div>

  <div class="field">
    <%= f.label :suppression %>
    <%= f.number_field :suppression %>
    <%= error_messages_on(f.object, :suppression)%>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
    <%= error_messages_on(f.object, :comment)%>
  </div>

  <div class="field">
    <% if card.image? %>
      <div class="thumbnail">
        <%= image_tag card.image.url %>
      </div>
    <% end %>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
    <%= error_messages_on(f.object, :image)%>
  </div>
  <div class="field">
    <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 -->
    <% if card.persisted? && card.image? %>
        <label>
          <%= f.check_box :remove_image %>
          画像を削除
        </label>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.number_field :cost %>
    <%= error_messages_on(f.object, :cost)%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th><%= Card.human_attribute_name :name %></th>
      <th><%= Card.human_attribute_name :rate %></th>
      <th><%= Card.human_attribute_name :group %></th>
      <th><%= Card.human_attribute_name :attack %></th>
      <th><%= Card.human_attribute_name :intellect %></th>
      <th><%= Card.human_attribute_name :suppression %></th>
      <th><%= Card.human_attribute_name :comment %></th>
      <th><%= Card.human_attribute_name :image %></th>
      <th><%= Card.human_attribute_name :cost %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
        <td><%= card.rate %></td>
        <td><%= card.group %></td>
        <td><%= card.attack %></td>
        <td><%= card.intellect %></td>
        <td><%= card.suppression %></td>
        <td><%= card.comment %></td>
        <td><%= card.image %></td>
        <td><%= card.cost %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Card.human_attribute_name :name %>:</strong>
  <%= @card.name %>
</p>

<p>
  <strong><%= Card.human_attribute_name :rate %>:</strong>
  <%= @card.rate %>
</p>

<p>
  <strong><%= Card.human_attribute_name :group %>:</strong>
  <%= @card.group %>
</p>

<p>
  <strong><%= Card.human_attribute_name :attack %>:</strong>
  <%= @card.attack %>
</p>

<p>
  <strong><%= Card.human_attribute_name :intellect %>:</strong>
  <%= @card.intellect %>
</p>

<p>
  <strong><%= Card.human_attribute_name :suppression %>:</strong>
  <%= @card.suppression %>
</p>

<p>
  <strong><%= Card.human_attribute_name :comment %>:</strong>
  <%= @card.comment %>
</p>

<p>
  <strong><%= Card.human_attribute_name :image %>:</strong>
  <% if @card.image? %>
    <div class="thumbnail">
      <%= image_tag @card.image.url %>
    </div>
  <% end %>
</p>

<p>
  <strong><%= Card.human_attribute_name :cost %>:</strong>
  <%= @card.cost %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CardCollection</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>